apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"StatefulSet","metadata":{"annotations":{},"creationTimestamp":"2025-06-21T21:18:29Z","generation":1,"name":"kafka","namespace":"default","resourceVersion":"856","uid":"7ec2c40c-1a30-4f36-8d0b-9fcd251e74ea"},"spec":{"persistentVolumeClaimRetentionPolicy":{"whenDeleted":"Retain","whenScaled":"Retain"},"podManagementPolicy":"OrderedReady","replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"kafka"}},"serviceName":"kafka","template":{"metadata":{"creationTimestamp":null,"labels":{"app":"kafka"}},"spec":{"containers":[{"args":["export KAFKA_ADVERTISED_LISTENERS=\"PLAINTEXT://$(hostname -f):9092\"\nexec /etc/confluent/docker/run\n"],"command":["/bin/sh","-c"],"env":[{"name":"KAFKA_BROKER_ID","value":"1"},{"name":"KAFKA_ZOOKEEPER_CONNECT","value":"zookeeper.default.svc.cluster.local:2181"},{"name":"KAFKA_LISTENER_SECURITY_PROTOCOL_MAP","value":"PLAINTEXT:PLAINTEXT"},{"name":"KAFKA_ADVERTISED_LISTENERS","value":"PLAINTEXT://kafka-$(POD_NAME).kafka.default.svc.cluster.local:9092"},{"name":"POD_NAME","valueFrom":{"fieldRef":{"apiVersion":"v1","fieldPath":"metadata.name"}}},{"name":"KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR","value":"1"},{"name":"KAFKA_AUTO_CREATE_TOPICS_ENABLE","value":"true"}],"image":"confluentinc/cp-kafka:7.4.0","imagePullPolicy":"IfNotPresent","name":"kafka","ports":[{"containerPort":9092,"protocol":"TCP"}],"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}},"updateStrategy":{"rollingUpdate":{"partition":0},"type":"RollingUpdate"}},"status":{"availableReplicas":0,"collisionCount":0,"currentReplicas":1,"currentRevision":"kafka-775bb86f86","observedGeneration":1,"replicas":1,"updateRevision":"kafka-775bb86f86","updatedReplicas":1}}
  creationTimestamp: "2025-06-21T21:18:29Z"
  generation: 1
  name: kafka
  namespace: default
  resourceVersion: "1058"
  uid: 7ec2c40c-1a30-4f36-8d0b-9fcd251e74ea
spec:
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: kafka
  serviceName: kafka
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kafka
    spec:
      containers:
      - args:
        - |
          export KAFKA_ADVERTISED_LISTENERS="PLAINTEXT://$(hostname -f):9092"
          exec /etc/confluent/docker/run
        command:
        - /bin/sh
        - -c
        env:
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper.default.svc.cluster.local:2181
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: PLAINTEXT:PLAINTEXT
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://kafka-$(POD_NAME).kafka.default.svc.cluster.local:9092
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
          value: "true"
        image: confluentinc/cp-kafka:7.4.0
        imagePullPolicy: IfNotPresent
        name: kafka
        ports:
        - containerPort: 9092
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
status:
  availableReplicas: 0
  collisionCount: 0
  currentReplicas: 1
  currentRevision: kafka-775bb86f86
  observedGeneration: 1
  replicas: 1
  updateRevision: kafka-775bb86f86
  updatedReplicas: 1
