apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-product
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-product
  template:
    metadata:
      labels:
        app: postgres-product
    spec:
      containers:
        - name: postgres
          image: postgres:13
          env:
            - name: POSTGRES_PRODUCT
              value: "butbzdorov"
            - name: POSTGRES_PASSWORD
              value: "102938asd"
            - name: POSTGRES_DB
              value: "product_service_db"
            - name: PGDATA
              value: "/var/lib/postgresql/data/pgdata"
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc-product

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-product
spec:
  selector:
    app: postgres-product
  ports:
    - port: 5432
      targetPort: 5432