apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"creationTimestamp":"2025-06-21T21:18:27Z","name":"redis","namespace":"default","resourceVersion":"1916","uid":"4fc7f005-d757-4d89-b2a0-85bd2d7952e2"},"spec":{"clusterIP":"10.99.180.209","clusterIPs":["10.99.180.209"],"internalTrafficPolicy":"Cluster","ipFamilies":["IPv4"],"ipFamilyPolicy":"SingleStack","ports":[{"port":6379,"protocol":"TCP","targetPort":6379}],"selector":{"app":"redis"},"sessionAffinity":"None","type":"ClusterIP"},"status":{"loadBalancer":{}}}
  creationTimestamp: "2025-06-21T21:33:36Z"
  name: redis
  namespace: default
  resourceVersion: "2202"
  uid: 6d2cfed0-f8f0-47d4-8ed8-c297553fc49e
spec:
  clusterIP: 10.99.180.209
  clusterIPs:
  - 10.99.180.209
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: redis
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
